services:
  aditrack:
    container_name : Adi-Track
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3456:3456"
    environment:
      - NODE_ENV=production
      - PORT=3456
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - /opt/aditrack:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3456/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

