// Données de test basées sur le tableau fourni dans le cahier des charges
export const mockGradesData = [
  {
    id: "1",
    date: "23/09/2024",
    code: "2425_A1_MATHS1_01",
    title: "DS Mathématiques 1 n°1 (S1)",
    grade: 9.5,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "2",
    date: "04/10/2024",
    code: "2425_A1_MATHS1_CC",
    title: "CC Mathématiques 1 (S1)",
    grade: 18.13,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "3",
    date: "04/10/2024",
    code: "2425_A1_MATHS1_PROJET",
    title: "Projet Mathématiques 1 (S1)",
    grade: 14.0,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "4",
    date: "07/10/2024",
    code: "2425_A1_INFO1_CARDUINO_01",
    title: "DS Informatique n°1 (S1)",
    grade: 15.0,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "5",
    date: "18/10/2024",
    code: "2425_A1_SCI1_ELECNUM_CC_01",
    title: "TP Élec Num (S1)",
    grade: 17.5,
    coefficient: 4,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "6",
    date: "21/10/2024",
    code: "2425_A1_MATHS2_01",
    title: "DS Mathématiques 2 n°1 (S1)",
    grade: 10.0,
    coefficient: 4,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "7",
    date: "21/10/2024",
    code: "2425_A1_SCI1_MACHINESOUTILS",
    title: "Formations Machines-Outils (S1)",
    grade: 0,
    coefficient: 0,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "8",
    date: "12/11/2024",
    code: "2425_A1_FHL1_FRANCAIS_01",
    title: "Inventer un objet",
    grade: 16.0,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "9",
    date: "12/11/2024",
    code: "2425_A1_FHL1_FRANCAIS_02",
    title: "Note de clarification",
    grade: 14.0,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "10",
    date: "12/11/2024",
    code: "2425_A1_FHL1_FRANCAIS_03",
    title: "Oral technique complexe",
    grade: 14.0,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  // Ajout d'un exemple d'absence non justifiée
  {
    id: "11",
    date: "18/11/2024",
    code: "2425_A1_MATHS2_02",
    title: "DS Mathématiques 2 n°2 (S1)",
    grade: 0,
    coefficient: 5,
    absence: true,
    absenceJustified: false,
  },
  // Ajout d'un exemple d'absence justifiée
  {
    id: "12",
    date: "18/11/2024",
    code: "2425_A1_MATHS2_CC",
    title: "CC Mathématiques 2",
    grade: 0,
    coefficient: 3,
    absence: true,
    absenceJustified: true,
  },
  {
    id: "13",
    date: "18/11/2024",
    code: "2425_A1_MATHS2_PROJET",
    title: "Projet Mathématiques 2 (S1)",
    grade: 14.0,
    coefficient: 8,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "14",
    date: "25/11/2024",
    code: "2425_A1_INFO1_WEB_CC",
    title: "CC Informatique (Web, S1)",
    grade: 16.0,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "15",
    date: "25/11/2024",
    code: "2425_A1_SCI1_MECA_01",
    title: "DS Mécanique n°1 (S1)",
    grade: 9.0,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "16",
    date: "02/12/2024",
    code: "2425_A1_PROJET1_GP_01",
    title: "Évaluation GP (S1)",
    grade: 13.25,
    coefficient: 2,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "17",
    date: "09/12/2024",
    code: "2425_A1_MATHS3_01",
    title: "DS Mathématiques 3 n°1 (S1)",
    grade: 8.5,
    coefficient: 4,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "18",
    date: "09/12/2024",
    code: "2425_A1_SCI1_ELECNUM_CC_02",
    title: "TP Elec Num (S1)",
    grade: 16.5,
    coefficient: 6,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "19",
    date: "16/12/2024",
    code: "2425_A1_MATHS3_PROJET",
    title: "Projet Mathématiques 3 (S1)",
    grade: 10.5,
    coefficient: 8,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "20",
    date: "13/01/2025",
    code: "2425_A1_MATHS3_02",
    title: "DS Mathématiques 3 n°2 (S1)",
    grade: 5.5,
    coefficient: 5,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "21",
    date: "13/01/2025",
    code: "2425_A1_SCI1_ELECNUM_01",
    title: "DS Elec Num (S1)",
    grade: 16.5,
    coefficient: 5,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "22",
    date: "09/01/2025",
    code: "2425_A1_FHL1_PPP_01",
    title: "Evaluation PPP - CV",
    grade: 18.0,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "23",
    date: "09/01/2025",
    code: "2425_A1_FHL1_PPP_02",
    title: "Evaluation PPP - pitch",
    grade: 17.0,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "24",
    date: "08/01/2025",
    code: "2425_A1_INFO1_CARDUINO_CC",
    title: "Informatique (S1)",
    grade: 9.0,
    coefficient: 1,
    absence: false,
    absenceJustified: false,
  },
  {
    id: "25",
    date: "08/01/2025",
    code: "2425_A1_MATHS3_CC",
    title: "Contrôle continu Mathématiques 3 (S1)",
    grade: 15.9,
    coefficient: 3,
    absence: false,
    absenceJustified: false,
  },
]

// Structure des UE et leurs coefficients
export const ueStructure = {
  MATHS: {
    name: "Mathématiques",
    ects: 6,
    courses: {
      MATHS1: {
        name: "Mathématiques 1",
        coefficient: 4,
        evaluations: {
          DS: { percentage: 33 },
          CC: { percentage: 33 },
          PROJET: { percentage: 34 },
        },
      },
      MATHS2: {
        name: "Mathématiques 2",
        coefficient: 7,
        evaluations: {
          DS1: { coefficient: 4 },
          DS2: { coefficient: 5 },
          CC: { coefficient: 3 },
          PROJET: { coefficient: 8 },
        },
      },
      MATHS3: {
        name: "Mathématiques 3",
        coefficient: 9,
        evaluations: {
          DS1: { coefficient: 4 },
          DS2: { coefficient: 5 },
          CC: { coefficient: 3 },
          PROJET: { coefficient: 8 },
        },
      },
    },
  },
  INFO: {
    name: "Informatique",
    ects: 6,
    courses: {
      INFO1: {
        name: "Informatique 1",
        coefficient: 4,
        evaluations: {
          CARDUINO: { coefficient: 2 },
          BUREAUTIQUE: { coefficient: 1 },
          WEB: { coefficient: 1 },
        },
      },
    },
  },
  SCI: {
    name: "Sciences",
    ects: 6,
    courses: {
      SCI1: {
        name: "Sciences 1",
        coefficient: 2,
        evaluations: {
          MECA: { coefficient: 1 },
          ELECNUM: { coefficient: 1 },
          MACHINESOUTILS: { coefficient: 0 },
        },
      },
    },
  },
  PROJ: {
    name: "Projets",
    ects: 6,
    courses: {
      PROJ1: {
        name: "Projets 1",
        coefficient: 10,
        evaluations: {
          ALPHA: { coefficient: 3 },
          BETA: { coefficient: 3 },
          GAMMA: { coefficient: 2 },
          GP: { coefficient: 2 },
        },
      },
    },
  },
  HUM: {
    name: "Humanités",
    ects: 6,
    courses: {
      FHL1: {
        name: "Formation Humaine et Linguistique 1",
        coefficient: 9,
        evaluations: {
          IPC: { coefficient: 2 },
          PPP: { coefficient: 2 },
          FRANCAIS: { coefficient: 2 },
          ANGLAIS: { coefficient: 3 },
        },
      },
    },
  },
}
