export async function extractDataFromPDF(file: File): Promise<any> {
  // In a real implementation, this would parse the PDF
  // For this demo, we'll return mock data based on the provided PDF content

  // Simulate processing time
  await new Promise((resolve) => setTimeout(resolve, 2000))

  // Mock data extracted from the PDF
  return {
    studentName: "Flavio COMBLEZ",
    birthDate: "28/05/2006",
    birthPlace: "LILLE - FRANCE",
    ine: "080273397CA",
    class: "ADI1 2024-2025",
    rank: 36,
    grades: [
      {
        date: "13/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_MATHS3_02",
        name: "DS Mathématiques 3 n°2 S1",
        subject: "Mathématiques 3",
        grade: 5.5,
        coefficient: 5,
        isWrittenExam: true,
        isContinuousAssessment: false,
        isProject: false,
      },
      {
        date: "13/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_SCI1_ELECNUM_01",
        name: "DS Elec Num S1",
        subject: "Electronique Numérique 1",
        grade: 16.5,
        coefficient: 5,
        isWrittenExam: true,
        isContinuousAssessment: false,
        isProject: false,
      },
      {
        date: "09/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_PPP_01",
        name: "Evaluation PPP - CV",
        subject: "Projet Professionnel et Personnel",
        grade: 18.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "09/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_PPP_02",
        name: "Evaluation PPP-pitch",
        subject: "Projet Professionnel et Personnel",
        grade: 17.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "08/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_INFO1_CARDUINO_CC",
        name: "Informatique S1",
        subject: "C Microcontrôleur et algorithmie 1",
        grade: 9.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "08/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_MATHS3_CC",
        name: "Contrôle continu Mathématiques 3 S1",
        subject: "Mathématiques 3",
        grade: 15.9,
        coefficient: 3,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "07/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_ANGLAIS_01",
        name: "Evaluation Anglais S1 - contrôle continu",
        subject: "Anglais",
        grade: 10.0,
        coefficient: 3,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "07/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_ANGLAIS_01",
        name: "Evaluation Anglais S1 - TOEIC List",
        subject: "Anglais",
        grade: 10.2,
        coefficient: 5,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "07/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_ANGLAIS_02",
        name: "Evaluation Anglais S1 - Global Exam",
        subject: "Anglais",
        grade: 19.0,
        coefficient: 2,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "07/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_INFO1_BUREAUTIQUE_01",
        name: "Bureautique S1",
        subject: "Bureautique",
        grade: 13.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "07/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_PROJET1_GAMMA",
        name: "Projet GAMMA S1",
        subject: "Projet Gamma",
        grade: 8.5,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: false,
        isProject: true,
      },
      {
        date: "06/01/2025",
        code: "2425_ADIMAKER_LILLE_A1_SCI1_MECA_02",
        name: "DS Mécanique n°2 S1",
        subject: "Mécanique 1",
        grade: 9.0,
        coefficient: 2,
        isWrittenExam: true,
        isContinuousAssessment: false,
        isProject: false,
      },
      {
        date: "25/12/2024",
        code: "2425_ADIMAKER_LILLE_A1_SCI1_ELECNUM_PROJ",
        name: "Projet Elec Num S1",
        subject: "Electronique Numérique 1",
        grade: 18.0,
        coefficient: 5,
        isWrittenExam: false,
        isContinuousAssessment: false,
        isProject: true,
      },
      {
        date: "20/12/2024",
        code: "2425_ADIMAKER_LILLE_A1_PROJET1_BETA",
        name: "Projet BETA S1",
        subject: "Projets Beta",
        grade: 8.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: false,
        isProject: true,
      },
      {
        date: "15/12/2024",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_IPC_QUIZ",
        name: "Quiz actualités S1",
        subject: "Introduction à la pensée critique",
        grade: 11.5,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "15/12/2024",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_IPC_PRES",
        name: "Présentation S1",
        subject: "Introduction à la pensée critique",
        grade: 14.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "10/12/2024",
        code: "2425_ADIMAKER_LILLE_A1_MATHS3_PROJ",
        name: "Projet Mathématiques 3 S1",
        subject: "Mathématiques 3",
        grade: 10.5,
        coefficient: 8,
        isWrittenExam: false,
        isContinuousAssessment: false,
        isProject: true,
      },
      {
        date: "05/12/2024",
        code: "2425_ADIMAKER_LILLE_A1_PROJET1_GP_CC",
        name: "Contrôle continu GP",
        subject: "Gestion de projet",
        grade: 6.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "01/12/2024",
        code: "2425_ADIMAKER_LILLE_A1_MATHS3_01",
        name: "DS Mathématiques 3 n°1 S1",
        subject: "Mathématiques 3",
        grade: 8.5,
        coefficient: 4,
        isWrittenExam: true,
        isContinuousAssessment: false,
        isProject: false,
      },
      {
        date: "25/11/2024",
        code: "2425_ADIMAKER_LILLE_A1_SCI1_ELECNUM_TP",
        name: "TP Elec Num S1",
        subject: "Electronique Numérique 1",
        grade: 16.5,
        coefficient: 6,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "20/11/2024",
        code: "2425_ADIMAKER_LILLE_A1_PROJET1_GP",
        name: "Evaluation GP",
        subject: "Gestion de projet",
        grade: 13.25,
        coefficient: 2,
        isWrittenExam: true,
        isContinuousAssessment: false,
        isProject: false,
      },
      {
        date: "15/11/2024",
        code: "2425_ADIMAKER_LILLE_A1_INFO1_WEB",
        name: "Informatique S1",
        subject: "Web 1",
        grade: 16.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "10/11/2024",
        code: "2425_ADIMAKER_LILLE_A1_MATHS2_02",
        name: "DS Mathématiques 2 n°2 S1",
        subject: "Mathématiques 2",
        grade: 8.75,
        coefficient: 5,
        isWrittenExam: true,
        isContinuousAssessment: false,
        isProject: false,
      },
      {
        date: "05/11/2024",
        code: "2425_ADIMAKER_LILLE_A1_MATHS2_CC",
        name: "Contrôle continu Mathématiques 2 S1",
        subject: "Mathématiques 2",
        grade: 18.89,
        coefficient: 3,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "01/11/2024",
        code: "2425_ADIMAKER_LILLE_A1_MATHS2_PROJ",
        name: "Projet Mathématiques 2 S1",
        subject: "Mathématiques 2",
        grade: 14.0,
        coefficient: 8,
        isWrittenExam: false,
        isContinuousAssessment: false,
        isProject: true,
      },
      {
        date: "25/10/2024",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_FR_OBJ",
        name: "Inventer un objet",
        subject: "Français",
        grade: 16.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "20/10/2024",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_FR_NOTE",
        name: "note de clarification",
        subject: "Français",
        grade: 14.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "15/10/2024",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_FR_ORAL",
        name: "oral technique complexe",
        subject: "Français",
        grade: 14.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "10/10/2024",
        code: "2425_ADIMAKER_LILLE_A1_MATHS2_01",
        name: "DS Mathématiques 2 n°1 S1",
        subject: "Mathématiques 1",
        grade: 10.0,
        coefficient: 4,
        isWrittenExam: true,
        isContinuousAssessment: false,
        isProject: false,
      },
      {
        date: "05/10/2024",
        code: "2425_ADIMAKER_LILLE_A1_SCI1_MACHINES",
        name: "Formations Machines-Outils",
        subject: "Machines-Outils",
        grade: 20.0,
        coefficient: 4,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "01/10/2024",
        code: "2425_ADIMAKER_LILLE_A1_SCI1_ELECNUM_TP",
        name: "TP Elec Num S1",
        subject: "Electronique Numérique 1",
        grade: 17.5,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "25/09/2024",
        code: "2425_ADIMAKER_LILLE_A1_INFO1_C_01",
        name: "DS Informatique n°1 S1",
        subject: "C Microcontrôleur et algorithmie 1",
        grade: 15.0,
        coefficient: 1,
        isWrittenExam: true,
        isContinuousAssessment: false,
        isProject: false,
      },
      {
        date: "20/09/2024",
        code: "2425_ADIMAKER_LILLE_A1_MATHS1_CC",
        name: "Contrôle continu Mathématiques 1 S1",
        subject: "Mathématiques 1",
        grade: 18.13,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "15/09/2024",
        code: "2425_ADIMAKER_LILLE_A1_MATHS1_PROJ",
        name: "Projet Mathématiques 1 S1",
        subject: "Mathématiques 1",
        grade: 14.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: false,
        isProject: true,
      },
      {
        date: "10/09/2024",
        code: "2425_ADIMAKER_LILLE_A1_MATHS1_01",
        name: "DS Informatique n°1 S1",
        subject: "Mathématiques 1",
        grade: 9.5,
        coefficient: 1,
        isWrittenExam: true,
        isContinuousAssessment: false,
        isProject: false,
      },
      {
        date: "05/09/2024",
        code: "2425_ADIMAKER_LILLE_A1_FHL1_COMM",
        name: "Communication interculturelle",
        subject: "Communication interculturelle",
        grade: 14.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: true,
        isProject: false,
      },
      {
        date: "01/09/2024",
        code: "2425_ADIMAKER_LILLE_A1_SCI1_MECA_PROJ",
        name: "Projet Mécanique S1",
        subject: "Mécanique 1",
        grade: 0.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: false,
        isProject: true,
      },
      {
        date: "25/08/2024",
        code: "2425_ADIMAKER_LILLE_A1_INFO1_WEB_01",
        name: "DS Informatique n°1 S1",
        subject: "Web 1",
        grade: 0.0,
        coefficient: 1,
        isWrittenExam: true,
        isContinuousAssessment: false,
        isProject: false,
      },
      {
        date: "20/08/2024",
        code: "2425_ADIMAKER_LILLE_A1_PROJET1_ALPHA",
        name: "Projets Alpha",
        subject: "Projets Alpha",
        grade: 13.0,
        coefficient: 1,
        isWrittenExam: false,
        isContinuousAssessment: false,
        isProject: true,
      },
    ],
  }
}

